#!/user/bin/env groovy

def groovyScript

pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    parameters {
        // string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'DOCKER_HUB_REPO_URL', defaultValue: 'hangrybear/devops_bootcamp', description: 'Enter your own docker hub repository')

        // booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'VERSION_NUM', choices: ['1.0', '1.1', '1.2', '1.3', '1.4', '1.5'], description: 'Pick a version number.')

        // password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    stages {
        stage('init') {
            steps {
                dir("java-app") {
                    script {
                        groovyScript = load "script.groovy"
                    }
                }
            }
        }
        stage('build app') {
            steps {
                dir("java-app") {
                    script {
                        groovyScript.buildApp()
                    }
                }
            }
        }
        stage('build image') {
            steps {
                dir("java-app") {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable: 'PASS', usernameVariable: 'USER')]){
                            groovyScript.buildImage()
                        }
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                dir("java-app") {
                    script {
                        groovyScript.deployApp()
                    }
                }
            }
        }
    }
}

